---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  # - name: freebsd-10.2

suites:
  - name: default
    run_list:
      - recipe[b-goapp::default]
    attributes:
      b-goapp:
        bin: "https://s3-eu-west-1.amazonaws.com/my-habitat/goapp/web"
